# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd5e268040fabc7eae3d1b5453a75d93"
name = "HN Template App"
handle = "hn-template-app"
application_url = "https://famous-reviewing-pottery-breeds.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_users"

[auth]
redirect_urls = ["https://famous-reviewing-pottery-breeds.trycloudflare.com/auth/callback", "https://famous-reviewing-pottery-breeds.trycloudflare.com/auth/shopify/callback", "https://famous-reviewing-pottery-breeds.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
